use super::parser::{Assignment, Block, Program, Value};
use crate::network::method::HttpMethod;

struct RouteEntry {
    method: HttpMethod,
    path: String,
    handler: String,
}

/// Generates Rust source code from a parsed Harpy [`Program`].
///
/// Each [`Block`] becomes a public function whose name comes from `block.handler_name`
pub fn generate_rust_code(program: &Program) -> String {
    let mut output = String::new();

    output.push_str("// Auto-generated by hc\n");
    output.push_str("// Do not edit this file manually.\n\n");

    let mut route_entries = Vec::new();

    for block in &program.blocks {
        let handler_name = resolve_handler_name(block);

        if let (Some(method), Some(path)) = (block.method.as_ref(), block.path.as_ref()) {
            route_entries.push(RouteEntry {
                method: *method,
                path: path.clone(),
                handler: handler_name.clone(),
            });
        }

        emit_handler(&mut output, block, &handler_name);
    }

    emit_router(&mut output, &route_entries);
    emit_main(&mut output, &route_entries);

    output
}

fn emit_handler(output: &mut String, block: &Block, handler_name: &str) {
    // Doc comment
    if let Some(ref docs) = block.docs {
        for line in docs.lines() {
            let trimmed = line.trim_start_matches('#').trim();
            output.push_str(&format!("/// {}\n", trimmed));
        }
    }

    output.push_str(&format!("pub fn {}() -> String {{\n", handler_name));
    emit_body(output, &block.body);
    output.push_str("}\n\n");
}

fn emit_router(output: &mut String, route_entries: &[RouteEntry]) {
    output.push_str("pub fn route(method: &str, path: &str) -> Option<String> {\n");
    output.push_str("    match (method, path) {\n");

    for entry in route_entries {
        output.push_str(&format!(
            "        ({:?}, {:?}) => Some({}()),\n",
            entry.method.as_str(),
            entry.path,
            entry.handler
        ));
    }

    output.push_str("        _ => None,\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
}

fn emit_main(output: &mut String, route_entries: &[RouteEntry]) {
    output.push_str("fn main() {\n");

    if let Some(default_route) = route_entries.first() {
        output.push_str(&format!(
            "    let _ = route({:?}, {:?});\n",
            default_route.method.as_str(),
            default_route.path
        ));
    }

    output.push_str("}\n");
}

/// Resolves the handler name for a block.
fn resolve_handler_name(block: &Block) -> String {
    if let Some(ref name) = block.handler_name {
        return name.clone();
    }

    let method = block
        .method
        .as_ref()
        .map(HttpMethod::as_str)
        .unwrap_or("route")
        .to_lowercase();
    let path_part = block
        .path
        .clone()
        .unwrap_or_default()
        .trim_start_matches('/')
        .replace('/', "_")
        .replace('-', "_");

    if path_part.is_empty() {
        method
    } else {
        format!("{}_{}", method, path_part)
    }
}

/// Emits Rust statements from block body assignments.
///
/// Assignments named `return` are emitted as explicit `return <expr>;` and end
/// code emission for the function body. If there are no assignments an empty
/// string literal is returned.
fn emit_body(output: &mut String, body: &[Assignment]) {
    if body.is_empty() {
        output.push_str("    String::new()\n");
        return;
    }

    for (i, assignment) in body.iter().enumerate() {
        let is_last = i == body.len() - 1;
        let rhs = match &assignment.value {
            Value::String(s) => {
                if assignment.name == "return" || assignment.name == "print" {
                    format!("{}", s)
                } else {
                    format!("{}.to_string()", s)
                }
            }
            Value::Execute(s) => {
                let fn_name = s.trim_start_matches('$');
                format!("{}()", fn_name)
            }
            Value::Print(inner) => {
                let inner_expr = match inner.as_ref() {
                    Value::String(s) => format!("{}", s),
                    Value::Execute(s) => {
                        let fn_name = s.trim_start_matches('$');
                        format!("{}()", fn_name)
                    }
                    Value::Print(_) => "String::new()".to_string(),
                };

                format!(
                    "{{ let __harpy_print_tmp = {inner_expr}; println!(\"{{}}\", __harpy_print_tmp); __harpy_print_tmp }}"
                )
            }
        };

        if assignment.name == "return" {
            output.push_str(&format!("    return {};\n", rhs));
            break;
        }

        if assignment.name == "print" {
            output.push_str(&format!("    println!(\"{{}}\", {});\n", rhs));

            if is_last {
                output.push_str("    String::new()\n");
            }
            continue;
        }

        if is_last {
            // Implicit return — just the expression
            output.push_str(&format!("    let {} = {};\n", assignment.name, rhs));
            output.push_str(&format!("    {}\n", assignment.name));
        } else {
            output.push_str(&format!("    let {} = {};\n", assignment.name, rhs));
        }
    }
}
