use super::parser::{Assignment, Block, Program, Value};

/// Generates Rust source code from a parsed Harpy [`Program`].
///
/// Each [`Block`] becomes a public function whose name comes from `block.handler_name`
pub fn generate_rust_code(program: &Program) -> String {
    let mut output = String::new();

    output.push_str("// Auto-generated by hc\n");
    output.push_str("// Do not edit this file manually.\n\n");

    for block in &program.blocks {
        let handler_name = resolve_handler_name(block);

        // Doc comment
        if let Some(ref docs) = block.docs {
            for line in docs.lines() {
                let trimmed = line.trim_start_matches('#').trim();
                output.push_str(&format!("/// {}\n", trimmed));
            }
        }

        output.push_str(&format!("pub fn {}() -> String {{\n", handler_name));

        emit_body(&mut output, &block.body);

        output.push_str("}\n\n");

        // Always append
        output.push_str("fn main(){\n");
        output.push_str(&format!("  {handler_name}();\n"));
        output.push_str("}");
    }

    output
}

/// Resolves the handler name for a block.
fn resolve_handler_name(block: &Block) -> String {
    if let Some(ref name) = block.handler_name {
        return name.clone();
    }

    let method = format!("{:?}", block.method).to_lowercase();
    let path_part = block
        .path
        .trim_start_matches('/')
        .replace('/', "_")
        .replace('-', "_");

    if path_part.is_empty() {
        method
    } else {
        format!("{}_{}", method, path_part)
    }
}

/// Emits Rust statements from block body assignments.
///
/// Assignments named `return` are emitted as explicit `return <expr>;` and end
/// code emission for the function body. If there are no assignments an empty
/// string literal is returned.
fn emit_body(output: &mut String, body: &[Assignment]) {
    if body.is_empty() {
        output.push_str("    String::new()\n");
        return;
    }

    for (i, assignment) in body.iter().enumerate() {
        let is_last = i == body.len() - 1;
        let rhs = match &assignment.value {
            Value::String(s) => {
                if assignment.name == "return" || assignment.name == "print" {
                    format!("{}", s)
                } else {
                    format!("{}.to_string()", s)
                }
            }
            Value::Execute(s) => {
                let fn_name = s.trim_start_matches('$');
                format!("{}()", fn_name)
            }
        };

        if assignment.name == "return" {
            output.push_str(&format!("    return {};\n", rhs));
            break;
        }

        if assignment.name == "print" {
            output.push_str(&format!("    println!(\"{{}}\", {});\n", rhs));

            if is_last {
                output.push_str("    String::new()\n");
            }
            continue;
        }

        if is_last {
            // Implicit return — just the expression
            output.push_str(&format!("    let {} = {};\n", assignment.name, rhs));
            output.push_str(&format!("    {}\n", assignment.name));
        } else {
            output.push_str(&format!("    let {} = {};\n", assignment.name, rhs));
        }
    }
}
